
gem "require_all", "~> 2.0"

gem "sinatra", "~> 2.0"

gem "shotgun", "~> 0.9.2"

gem "activerecord", "~> 5.2"

gem "sinatra-activerecord", "~> 2.0"

gem "sqlite3", "~> 1.4"

gem "pry", "~> 0.12.2"

gem "nokogiri", "~> 1.10"
