

const ADD_VILLAIN = "ADD_VILLAIN"
const ARREST_VILLAIN = "ARREST_VILLAIN"
const ADD_INFORMATION = "ADD_INFORMATION"
const REMOVE_INFORMATION = "REMOVE_INFORMATION"
const ADD_MORIARTY_LOCATION = "ADD_MORIARTY_LOCATION"

export {
    ADD_INFORMATION,
    ADD_VILLAIN,
    ARREST_VILLAIN,
    REMOVE_INFORMATION,
    ADD_MORIARTY_LOCATION
}